### ISSUE TITLE
This does not seem to work with Stream Deck 6.7.3 (21005)

### ISSUE THREAD

**Issue by smorked** [mongeon/MattermostAPI#27]
**Describe the bug**

**To Reproduce**
1. Go to https://marketplace.elgato.com/product/mmstreamdeck-801cecdc-91ec-41cf-a30c-b3bac5e76b08
2. Try to install with Stream Deck
3. See error "Unable to install MM.StreamDeck plugin"

**Expected behavior**
This should install, not error. 

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Used Firefox.
 - Version Streamdeck Version: 6.7.3 (21005)

Have you tried this recently? 
Thanks!

**Comment by smorked** [comment]
Ignore this. This installed correctly after I tried a 3rd time.

**Comment by mongeon** [comment]
That was a fast resolution. Let me know if you have any other issues.
